steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/web/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_API_URL}
      - -t
      - ${_IMAGE}
      - apps/web
images:
  - ${_IMAGE}
